version: '3.4'
services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-defra-id-net

  ################################################################################

  cdp-defra-id-stub:
    build: ./
    ports:
      - '3200:3200'
    links:
      - 'redis:redis'
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      PORT: 3200
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - cdp-defra-id-net

################################################################################

networks:
  cdp-defra-id-net:
    driver: bridge
